/*
 ユーザDB（東京地区システム用）テーブルリネーム・削除T-SQL
 作成者:K.Tanaka
 変更日付   Rev   変更履歴内容----------------------------->
 2017/06/30(0.1.0)新規作成
 2017/07/11(0.2.0)主キー削除、リネーム追加
 2017/07/25(0.3.0)PERSON_OF_COMPANY,PERSON_OF_OTHER_COMPANYインデックス追加
 2017/07/25(0.3.1)PERSON_OF_OTHER_COMPANY主キー削除
 2017/07/26(0.3.2)主キー削除処理追加
*/

USE [JINJI]
GO

-- 予備テーブル削除
/*** PK__BK_PERSON_OF_COMPANY 主キー削除(2017/7/25) ***/
if object_id('dbo.PK__BK_PERSON_OF_COMPANY') is not null
ALTER TABLE BK_PERSON_OF_COMPANY DROP CONSTRAINT PK__BK_PERSON_OF_COMPANY;
IF EXISTS(SELECT * FROM sys.indexes WHERE object_id = object_id('dbo.BK_PERSON_OF_COMPANY') AND NAME ='IDX_BK_PERSON_OF_COMPANY')
DROP INDEX IDX_BK_PERSON_OF_COMPANY ON dbo.BK_PERSON_OF_COMPANY;
if object_id('dbo.BK_PERSON_OF_COMPANY') is not null
DROP TABLE BK_PERSON_OF_COMPANY;

/*** PK__BK_PERSON_OF_OTHER_COMPANY 主キー削除(2017/7/25) ***/
if object_id('dbo.PK__BK_PERSON_OF_OTHER_COMPANY') is not null
ALTER TABLE BK_PERSON_OF_OTHER_COMPANY DROP CONSTRAINT PK__BK_PERSON_OF_OTHER_COMPANY;
IF EXISTS(SELECT * FROM sys.indexes WHERE object_id = object_id('dbo.BK_PERSON_OF_OTHER_COMPANY') AND NAME ='IDX_BK_PERSON_OF_OTHER_COMPANY')
DROP INDEX IDX_BK_PERSON_OF_OTHER_COMPANY ON dbo.BK_PERSON_OF_OTHER_COMPANY;
if object_id('dbo.BK_PERSON_OF_OTHER_COMPANY') is not null
DROP TABLE BK_PERSON_OF_OTHER_COMPANY;

if object_id('dbo.PK__BK_BU_INFORMATION') is not null
ALTER TABLE BK_BU_INFORMATION DROP CONSTRAINT PK__BK_BU_INFORMATION;
if object_id('dbo.BK_BU_INFORMATION') is not null
DROP TABLE BK_BU_INFORMATION;

if object_id('dbo.PK__BK_SHITSU_INFORMATION') is not null
ALTER TABLE BK_SHITSU_INFORMATION DROP CONSTRAINT PK__BK_SHITSU_INFORMATION;
if object_id('dbo.BK_SHITSU_INFORMATION') is not null
DROP TABLE BK_SHITSU_INFORMATION;

if object_id('dbo.PK__BK_KAKARI_INFORMATION') is not null
ALTER TABLE BK_KAKARI_INFORMATION DROP CONSTRAINT PK__BK_KAKARI_INFORMATION;
if object_id('dbo.BK_KAKARI_INFORMATION') is not null
DROP TABLE BK_KAKARI_INFORMATION;

if object_id('dbo.PK__BK_STAFF_DIVISION') is not null
ALTER TABLE BK_STAFF_DIVISION DROP CONSTRAINT PK__BK_STAFF_DIVISION;
if object_id('dbo.BK_STAFF_DIVISION') is not null
DROP TABLE BK_STAFF_DIVISION;

if object_id('dbo.PK__BK_ABOUT_WORK') is not null
ALTER TABLE BK_ABOUT_WORK DROP CONSTRAINT PK__BK_ABOUT_WORK;
if object_id('dbo.BK_ABOUT_WORK') is not null
DROP TABLE BK_ABOUT_WORK;

if object_id('dbo.PK__BK_JOB_CATEGORY') is not null
ALTER TABLE BK_JOB_CATEGORY DROP CONSTRAINT PK__BK_JOB_CATEGORY;
if object_id('dbo.BK_JOB_CATEGORY') is not null
DROP TABLE BK_JOB_CATEGORY;

/*** PK__BK_QUALIFICATION 主キー削除(2017/7/25) ***/
if object_id('dbo.PK__BK_QUALIFICATION') is not null
ALTER TABLE BK_QUALIFICATION DROP CONSTRAINT PK__BK_QUALIFICATION;
if object_id('dbo.BK_QUALIFICATION') is not null
DROP TABLE BK_QUALIFICATION;

-- 号口テーブルリネーム
/*** PK__PERSON_OF_COMPANY 主キー削除(2017/7/25) ***/
if object_id('dbo.PK__PERSON_OF_COMPANY') is not null
ALTER TABLE PERSON_OF_COMPANY DROP CONSTRAINT PK__PERSON_OF_COMPANY;
IF EXISTS(SELECT * FROM sys.indexes WHERE object_id = object_id('dbo.PERSON_OF_COMPANY') AND NAME ='IDX_PERSON_OF_COMPANY')
DROP INDEX IDX_PERSON_OF_COMPANY ON dbo.PERSON_OF_COMPANY;
if object_id('dbo.PERSON_OF_COMPANY') is not null
EXEC sp_rename 'dbo.PERSON_OF_COMPANY', 'BK_PERSON_OF_COMPANY';
CREATE INDEX IDX_BK_PERSON_OF_COMPANY ON BK_PERSON_OF_COMPANY(STAFF_CODE, ORIGINAL_BELONGING_START_DATE, ORIGINAL_BELONGING_CODE)

/*** PK__PERSON_OF_OTHER_COMPANY 主キー削除(2017/7/25) ***/
if object_id('dbo.PK__PERSON_OF_OTHER_COMPANY') is not null
ALTER TABLE PERSON_OF_OTHER_COMPANY DROP CONSTRAINT PK__PERSON_OF_OTHER_COMPANY;
IF EXISTS(SELECT * FROM sys.indexes WHERE object_id = object_id('dbo.PERSON_OF_OTHER_COMPANY') AND NAME ='IDX_PERSON_OF_OTHER_COMPANY')
DROP INDEX IDX_PERSON_OF_OTHER_COMPANY ON dbo.PERSON_OF_OTHER_COMPANY;
if object_id('dbo.PERSON_OF_OTHER_COMPANY') is not null
EXEC sp_rename 'dbo.PERSON_OF_OTHER_COMPANY', 'BK_PERSON_OF_OTHER_COMPANY';
CREATE INDEX IDX_BK_PERSON_OF_OTHER_COMPANY ON BK_PERSON_OF_OTHER_COMPANY(STAFF_CODE)

if object_id('dbo.PK__BU_INFORMATION') is not null
EXEC sp_rename 'BU_INFORMATION.PK__BU_INFORMATION', 'PK__BK_BU_INFORMATION';
if object_id('dbo.BU_INFORMATION') is not null
EXEC sp_rename 'dbo.BU_INFORMATION', 'BK_BU_INFORMATION';

if object_id('dbo.PK__SHITSU_INFORMATION') is not null
EXEC sp_rename 'SHITSU_INFORMATION.PK__SHITSU_INFORMATION', 'PK__BK_SHITSU_INFORMATION';
if object_id('dbo.SHITSU_INFORMATION') is not null
EXEC sp_rename 'dbo.SHITSU_INFORMATION', 'BK_SHITSU_INFORMATION';

if object_id('dbo.PK__KAKARI_INFORMATION') is not null
EXEC sp_rename 'KAKARI_INFORMATION.PK__KAKARI_INFORMATION', 'PK__BK_KAKARI_INFORMATION';
if object_id('dbo.KAKARI_INFORMATION') is not null
EXEC sp_rename 'dbo.KAKARI_INFORMATION', 'BK_KAKARI_INFORMATION';

if object_id('dbo.PK__STAFF_DIVISION') is not null
EXEC sp_rename 'STAFF_DIVISION.PK__STAFF_DIVISION', 'PK__BK_STAFF_DIVISION';
if object_id('dbo.STAFF_DIVISION') is not null
EXEC sp_rename 'dbo.STAFF_DIVISION', 'BK_STAFF_DIVISION';

if object_id('dbo.PK__ABOUT_WORK') is not null
EXEC sp_rename 'ABOUT_WORK.PK__ABOUT_WORK', 'PK__BK_ABOUT_WORK';
if object_id('dbo.ABOUT_WORK') is not null
EXEC sp_rename 'dbo.ABOUT_WORK', 'BK_ABOUT_WORK';

if object_id('dbo.PK__JOB_CATEGORY') is not null
EXEC sp_rename 'JOB_CATEGORY.PK__JOB_CATEGORY', 'PK__BK_JOB_CATEGORY';
if object_id('dbo.JOB_CATEGORY') is not null
EXEC sp_rename 'dbo.JOB_CATEGORY', 'BK_JOB_CATEGORY';

/*** PK__QUALIFICATION 主キー削除(2017/7/25) ***/
if object_id('dbo.PK__QUALIFICATION') is not null
ALTER TABLE QUALIFICATION DROP CONSTRAINT PK__QUALIFICATION;
if object_id('dbo.QUALIFICATION') is not null
EXEC sp_rename 'dbo.QUALIFICATION', 'BK_QUALIFICATION';

-- ワークテーブルリネーム
/*** PK__WK_PERSON_OF_COMPANY 主キー削除(2017/7/25) ***/
if object_id('dbo.PK__WK_PERSON_OF_COMPANY') is not null
ALTER TABLE WK_PERSON_OF_COMPANY DROP CONSTRAINT PK__WK_PERSON_OF_COMPANY;
IF EXISTS(SELECT * FROM sys.indexes WHERE object_id = object_id('dbo.WK_PERSON_OF_COMPANY') AND NAME ='IDX_WK_PERSON_OF_COMPANY')
DROP INDEX IDX_WK_PERSON_OF_COMPANY ON dbo.WK_PERSON_OF_COMPANY;
EXEC sp_rename 'dbo.WK_PERSON_OF_COMPANY', 'PERSON_OF_COMPANY';
CREATE INDEX IDX_PERSON_OF_COMPANY ON PERSON_OF_COMPANY(STAFF_CODE, ORIGINAL_BELONGING_START_DATE, ORIGINAL_BELONGING_CODE)

/*** PK__WK_PERSON_OF_OTHER_COMPANY 主キー削除(2017/7/25) ***/
if object_id('dbo.PK__WK_PERSON_OF_OTHER_COMPANY') is not null
ALTER TABLE WK_PERSON_OF_OTHER_COMPANY DROP CONSTRAINT PK__WK_PERSON_OF_OTHER_COMPANY;
IF EXISTS(SELECT * FROM sys.indexes WHERE object_id = object_id('dbo.WK_PERSON_OF_OTHER_COMPANY') AND NAME ='IDX_WK_PERSON_OF_OTHER_COMPANY')
DROP INDEX IDX_WK_PERSON_OF_OTHER_COMPANY ON dbo.WK_PERSON_OF_OTHER_COMPANY;
EXEC sp_rename 'dbo.WK_PERSON_OF_OTHER_COMPANY', 'PERSON_OF_OTHER_COMPANY';
CREATE INDEX IDX_PERSON_OF_OTHER_COMPANY ON PERSON_OF_OTHER_COMPANY(STAFF_CODE)

EXEC sp_rename 'dbo.WK_BU_INFORMATION', 'BU_INFORMATION';
EXEC sp_rename 'BU_INFORMATION.PK__WK_BU_INFORMATION', 'PK__BU_INFORMATION';

EXEC sp_rename 'dbo.WK_SHITSU_INFORMATION', 'SHITSU_INFORMATION';
EXEC sp_rename 'SHITSU_INFORMATION.PK__WK_SHITSU_INFORMATION', 'PK__SHITSU_INFORMATION';

EXEC sp_rename 'dbo.WK_KAKARI_INFORMATION', 'KAKARI_INFORMATION';
EXEC sp_rename 'KAKARI_INFORMATION.PK__WK_KAKARI_INFORMATION', 'PK__KAKARI_INFORMATION';

EXEC sp_rename 'dbo.WK_STAFF_DIVISION', 'STAFF_DIVISION';
EXEC sp_rename 'STAFF_DIVISION.PK__WK_STAFF_DIVISION', 'PK__STAFF_DIVISION';

EXEC sp_rename 'dbo.WK_ABOUT_WORK', 'ABOUT_WORK';
EXEC sp_rename 'ABOUT_WORK.PK__WK_ABOUT_WORK', 'PK__ABOUT_WORK';

EXEC sp_rename 'dbo.WK_JOB_CATEGORY', 'JOB_CATEGORY';
EXEC sp_rename 'JOB_CATEGORY.PK__WK_JOB_CATEGORY', 'PK__JOB_CATEGORY';

/*** PK__WK_QUALIFICATION 主キー削除(2017/7/25) ***/
if object_id('dbo.PK__WK_QUALIFICATION') is not null
ALTER TABLE WK_QUALIFICATION DROP CONSTRAINT PK__WK_QUALIFICATION;
EXEC sp_rename 'dbo.WK_QUALIFICATION', 'QUALIFICATION';
